sudo: required
services:
  - docker

# add builds for any test containers, for this we are only building the react app
before_install:
  - docker build -t jeffmacks/react-test -f ./client/Dockerfile.dev ./client
# if we built other images that we wanted to test above, run the testing scripts below
script:
  - docker run -e CI=true jeffmacks/react-test npm test
# after tests pass, build all for images
after_success:
  - docker build -t jeffmacks/multi-client ./client
  - docker build -t jeffmacks/multi-nginx ./nginx
  - docker build -t jeffmacks/multi-server ./server
  - docker build -t jeffmacks/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push all the build images to docker hub
  - docker push jeffmacks/multi-client
  - docker push jeffmacks/multi-nginx
  - docker push jeffmacks/multi-server
  - docker push jeffmacks/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-631563120259
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
